### ISSUE TITLE
Autocomplete doesn't work on sequence nodes 

### ISSUE THREAD

**Issue by JPinkney** [JPinkney/vscode-k8s#43]
```
spec:
  containers:
    ports:
      - containerPort: 80
```

Container port won't autocomplete
