### ISSUE TITLE
Ilegal argument: line must be positive

### ISSUE THREAD

**Issue by JPinkney** [JPinkney/vscode-k8s#52]
```
apiVersion: kind: ConfigMap3
metadata:
  name: f8tenant.secrets
  namespace: default
```

Should error but instead it fails with message "Illegal argument: line must be positive"
