### ISSUE TITLE
Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by JPinkney** [JPinkney/vscode-k8s#58]
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: glide
  namespace: default
data:
  
```

Gives:
[Error - 3:31:03 PM] Request textDocument/completion failed.
  Message: Request textDocument/completion failed with message: Cannot convert undefined or null to object
  Code: -32603
